PIPELINE: Add test fixtures and one test for bone_segmentation pipeline
nbckr/HoloRepository-Core pull request #75
Opened 2019-08-24 19:24 UTC by nbckr

2019-08-25 17:26 UTC, nbckr commented
**Update**: Added tests for all three pipelines .
* The abdominal_organs is disabled, needs some more massaging to run. Assuming it does run, total test coverage back up to ~72%
* I know that the 3 tests are currently quite similar. But i don't want to overcomplicate by combining and parametrising them more. Also I think they can be made more specific, checking that the correct chain of components was invoked etc.

2019-08-27 22:01 UTC, nbckr commented on HoloPipelines/tests/utils/shared_fixtures.py
> +    return mock_send_to_accessor
Could probably be in-line

2019-09-08 11:19 UTC, boonwj commented
Tests all appear to run well, though there was one part that threw me off. But it seems that was intended.

![image](https://user-images.githubusercontent.com/3538312/64487445-c82b7600-d232-11e9-81a3-4505fdeb3def.png)

Anyway, there is currently a merge conflict that is preventing this from being merged.

2019-09-08 12:13 UTC, boonwj requested changes
Resolve merge conflicts

2019-09-08 17:33 UTC, nbckr commented
Yes, the error is expected, it stems from `test_check_job_request_validity_invalid`. Agree that it may look confusing but I think this is acceptable. I'll sort out the merge conflicts.

2019-09-08 17:53 UTC, nbckr commented
Resolved conflicts and verified that the build pipeline runs the tests happily.

2019-09-08 20:58 UTC, boonwj approved these changes
All tests pass. Tests that uses the `imagingStudyEndpoint` are dependent on our hosted files. We should remember letting it be known during the handover.

2019-09-18 12:58 UTC, merged